"""
Django settings for your TOM project.

Originally generated by 'django-admin startproject' using Django 2.1.1.
Generated by ./manage.py tom_setup on Sept. 26, 2024, 12:47 p.m.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import tempfile

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1c1nvy&amp;t@z+wq16gbfag8_-t&amp;e#mppk4h=syp*i*fs^hi&amp;7ihi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tlister-thinkmate.lco.gtn',
]


# Application definition

TOM_NAME = 'FOMO'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_tasks',
    'django_tasks.backends.database',
    'guardian',
    'tom_common',
    'django_comments',
    'django_bootstrap5',
    'crispy_bootstrap5',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_tables2',
    'django_gravatar',
    'django_htmx',
    'tom_targets',
    'tom_alerts',
    'tom_observations',
    'tom_dataproducts',
    'tom_dataservices',
    'tom_calendar',
    'solsys_code',
    'solsys_code.solsys_code_observatory.apps.SolsysCodeObservatoryConfig',
    'tom_alertstreams',
    'tom_fink',
    'tom_registration',
    'tom_eso',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'tom_common.middleware.Raise403Middleware',
    'tom_common.middleware.ExternalServiceMiddleware',
    'tom_common.middleware.AuthStrategyMiddleware',
    'tom_common.middleware.AuthStrategyMiddleware',
    'tom_registration.middleware.RedirectAuthenticatedUsersFromRegisterMiddleware',
]

ROOT_URLCONF = 'fomo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# django-crispy-forms validates the {% crispy %} tag's template_pack against
# CRISPY_ALLOWED_TEMPLATE_PACKS, which defaults to ('uni_form', 'bootstrap3', 'bootstrap4') --
# 'bootstrap5' must be added explicitly or every {% crispy form %} render raises
# TemplateSyntaxError (missed during the BS4->BS5 migration; surfaced by the Playwright
# ephemeris-form functional test).
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap4', 'bootstrap5')
CRISPY_TEMPLATE_PACK = 'bootstrap5'

WSGI_APPLICATION = 'fomo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# FOMO_DATABASE_PATH lets the pre-executed demo notebooks under
# docs/notebooks/pre_executed/ run against a throwaway copy of the developer database
# instead of writing through to it (UAT G-33-4). An unset (or empty-string) variable
# leaves every command, test run and dev server pointed at fomo_db.sqlite3 exactly as
# before. Production overrides still belong in local_settings.py.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('FOMO_DATABASE_PATH') or os.path.join(BASE_DIR, 'fomo_db.sqlite3'),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = '/data/'

# The root logger's INFO level is load-bearing for the unattended path's credential hygiene
# (Phase 36, SC 4 / D-17): two DEBUG-level sites format a raw exception message from a portal
# call (backfill_lco_observations.py `_resolve_schedule`, unattended.py `step_reconcile`), which
# can carry an API key or the heartbeat ping URL. Accepted as-is on 2026-09-18 (36-UAT.md Test 2,
# 36-REVIEW.md WR-22) on the condition that this level stays at INFO. Before raising it to DEBUG
# -- in local_settings.py or here -- change both sites to log `type(exc).__name__` only and add
# the assertLogs(level='DEBUG') hygiene test WR-22 describes.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {'': {'handlers': ['console'], 'level': 'INFO'}},
}

# Caching
# https://docs.djangoproject.com/en/dev/topics/cache/#filesystem-caching

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': tempfile.gettempdir(),
    }
}

# TOM Specific configuration
TARGET_TYPE = 'NON_SIDEREAL'

# Set to the full path of a custom target model to extend the BaseTarget Model with custom fields.
# TARGET_MODEL_CLASS = 'solsys_code.models.UserDefinedTarget'

# Define MATCH_MANAGERS here. This is a dictionary that contains a dotted module path to the desired match manager
# for a given model.
# For example:
# MATCH_MANAGERS = {
#    "Target": "custom_code.match_managers.CustomTargetMatchManager"
# }
MATCH_MANAGERS = {}

FACILITIES = {
    'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': '',
    },
    # SOAR authenticates against the same LCO Observation Portal credentials (D-05),
    # so this entry mirrors 'LCO' exactly. It exists so SOARSettings('SOAR') resolves
    # a real 'api_key' key (D-04); 'portal_url' already resolves via LCOSettings'
    # inherited default even without this entry.
    # IN-31 (36-REVIEW.md iteration 5): if this 'portal_url' is ever repointed away from
    # observe.lco.global (e.g. a NOIRLab-hosted SOAR portal), remove the
    # FACILITIES['SOAR']['api_key'] line from the LCO_API_KEY fold at the end of this file --
    # it copies the LCO portal key, and repointing this URL without removing that line sends
    # the LCO Observation Portal key to a third-party host.
    'SOAR': {
        'portal_url': 'https://observe.lco.global',
        'api_key': '',
    },
    'GEM': {
        'portal_url': {
            'GS': 'https://139.229.34.15:8443',
            'GN': 'https://128.171.88.221:8443',
        },
        'api_key': {
            'GS': '',
            'GN': '',
        },
        'user_email': '',
        'programs': {
            'GS-YYYYS-T-NNN': {'MM': 'Std: Some descriptive text', 'NN': 'Rap: Some descriptive text'},
            'GN-YYYYS-T-NNN': {
                'QQ': 'Std: Some descriptive text',
                'PP': 'Rap: Some descriptive text',
            },
        },
    },
}

# Define the valid data product types for your TOM.
# This is a dictionary of tuples to be used as ChoiceField options, with the first element being the type and the
# second being the display name.
# Be careful when removing items, as previously valid types will no
# longer be valid, and may cause issues unless the offending records are modified.
DATA_PRODUCT_TYPES = {
    'photometry': ('photometry', 'Photometry'),
    'fits_file': ('fits_file', 'FITS File'),
    'spectroscopy': ('spectroscopy', 'Spectroscopy'),
    'image_file': ('image_file', 'Image File'),
}

DATA_PROCESSORS = {
    'photometry': 'tom_dataproducts.processors.photometry_processor.PhotometryProcessor',
    'spectroscopy': 'tom_dataproducts.processors.spectroscopy_processor.SpectroscopyProcessor',
}

TOM_FACILITY_CLASSES = [
    'tom_observations.facilities.lco.LCOFacility',
    'tom_observations.facilities.lco_redirect.LCORedirectFacility',
    'tom_observations.facilities.gemini.GEMFacility',
    'tom_observations.facilities.soar.SOARFacility',
    'tom_eso.eso.ESOFacility',
    #    'fomo.facilities.rubin.VROFacility',
    #    'fomo.facilities.LDT.LDTFacility'
]

TOM_REGISTRATION = {
    'REGISTRATION_AUTHENTICATION_BACKEND': 'django.contrib.auth.backends.ModelBackend',
    'REGISTRATION_REDIRECT_PATTERN': 'home',
    'REGISTRATION_STRATEGY': 'open',  # ['open', 'approval_required']
    # Optional email behavior if `REGISTRATION_STRATEGY = 'approval_required'`, default is False
    'SEND_APPROVAL_EMAILS': False,
    # Optional subject line of approval email, (Default Shown)
    #'APPROVAL_SUBJECT': f'Your {TOM_NAME} registration has been approved!',
    # Optional html-enabled body for approval email, (Default Shown)
    #'APPROVAL_MESSAGE': f'Your {TOM_NAME} registration has been approved. \
    #    You can log in <a href="mytom.com/login">here</a>.'
}

TOM_ALERT_CLASSES = [
    'tom_alerts.brokers.alerce.ALeRCEBroker',
    #  'tom_alerts.brokers.antares.ANTARESBroker',
    'tom_alerts.brokers.gaia.GaiaBroker',
    'tom_alerts.brokers.lasair.LasairBroker',
    'tom_alerts.brokers.tns.TNSBroker',
]

ALERT_STREAMS = [
    {
        'ACTIVE': True,
        'NAME': 'tom_fink.alertstream.FinkAlertStream',
        'OPTIONS': {
            'URL': os.getenv('FINK_CREDENTIAL_URL', 'set FINK_CREDENTIAL_URL value in environment'),
            'USERNAME': os.getenv('FINK_CREDENTIAL_USERNAME', 'set FINK_CREDENTIAL_USERNAME value in environment'),
            'GROUP_ID': os.getenv('FINK_CREDENTIAL_GROUP_ID', 'set FINK_CREDENTIAL_GROUP_ID value in environment'),
            'TOPIC': os.getenv('FINK_TOPIC', 'set FINK_TOPIC value in environment'),
            'MAX_POLL_NUMBER': os.getenv('FINK_MAX_POLL_NUMBER', 1e10),
            'TIMEOUT': os.getenv('FINK_TIMEOUT', 10),
            'TOPIC_HANDLERS': {
                'fink.stream': 'tom_fink.alertstream.alert_logger',
            },
        },
    },
]

BROKERS = {
    'TNS': {
        'api_key': '',
        'bot_id': '',
        'bot_name': '',
    },
    'LASAIR': {
        'api_key': os.getenv('LASAIR_TOKEN', ''),
    },
}

# Per-service configuration for tom_dataservices DataServices (catalog services such as
# MPC Explorer, Simbad, TNS, ... are auto-registered in tomtoolkit 3.0)
DATA_SERVICES = {}

# Define extra target fields here. Types can be any of "number", "string", "boolean" or "datetime"
# See https://tomtoolkit.github.io/docs/target_fields for documentation on this feature
# For example:
# EXTRA_FIELDS = [
#     {'name': 'redshift', 'type': 'number'},
#     {'name': 'discoverer', 'type': 'string'},
#     {'name': 'eligible', 'type': 'boolean'},
#     {'name': 'discovery_date', 'type': 'datetime'}
# ]
EXTRA_FIELDS = []

# Authentication strategy can either be LOCKED (required login for all views)
# or READ_ONLY (read only access to views)
AUTH_STRATEGY = 'READ_ONLY'

# Row-level data permissions restrict users from viewing certain objects unless they are a member of the group to which
# the object belongs. Setting this value to True will allow all `ObservationRecord`, `DataProduct`, and `ReducedDatum`
# objects to be seen by everyone. Setting it to False will allow users to specify which groups can access
# `ObservationRecord`, `DataProduct`, and `ReducedDatum` objects.
TARGET_PERMISSIONS_ONLY = True


# Default permission for newly created targets. Values can be 'PRIVATE', 'PUBLIC', or 'OPEN'
# Set FOMO default to 'OPEN' (visible to everyone, even when not logged in)
TARGET_DEFAULT_PERMISSION = 'OPEN'

# URLs that should be allowed access even with AUTH_STRATEGY = LOCKED
# for example: OPEN_URLS = ['/', '/about']
OPEN_URLS = []

HOOKS = {
    'target_post_save': 'tom_common.hooks.target_post_save',
    'observation_change_state': 'tom_common.hooks.observation_change_state',
    'data_product_post_upload': 'tom_dataproducts.hooks.data_product_post_upload',
    'data_product_post_save': 'tom_dataproducts.hooks.data_product_post_save',
    'multiple_data_products_post_save': 'tom_dataproducts.hooks.multiple_data_products_post_save',
}

AUTO_THUMBNAILS = False

THUMBNAIL_MAX_SIZE = (0, 0)

THUMBNAIL_DEFAULT_SIZE = (200, 200)

HINTS_ENABLED = True
HINT_LEVEL = 20

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

# Default Plotly theme setting, can set to any valid theme:
# 'plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn', 'simple_white', 'none'
PLOTLY_THEME = 'plotly_white'

# Dev default: prints emails to the runserver console instead of hanging on a real SMTP
# connection to localhost:25. Production must set a real EMAIL_BACKEND/EMAIL_HOST/
# EMAIL_HOST_USER/EMAIL_HOST_PASSWORD/DEFAULT_FROM_EMAIL in local_settings.py (below).
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Phase 36 (SCHED-08/09/10, D-15): the unattended runner's own configuration -- every value
# is environment-sourced, none is ever a CLI argument or embedded in the committed crontab
# template. Follows the FOMO_DATABASE_PATH single-setting os.getenv() shape above.
# FOMO_BASE_URL: used to build the admin/calendar links the failure email quotes (D-14).
FOMO_BASE_URL = os.getenv('FOMO_BASE_URL', 'http://localhost:8000')
# FOMO_HEARTBEAT_URL: no default -- an unset variable is None, which selects D-12's "off"
# branch (the runner logs one INFO line per tick and skips pinging).
FOMO_HEARTBEAT_URL = os.getenv('FOMO_HEARTBEAT_URL')
# FOMO_LOCK_DIR: directory for the runner's own per-command fcntl locks (same file the
# crontab template's `flock -n` guards for the runner as a whole).
FOMO_LOCK_DIR = os.getenv('FOMO_LOCK_DIR', '/var/lock/fomo')
# FOMO_STATE_DIR: directory for the D-11 suppression-state file. Defaults to FOMO_LOCK_DIR
# ("the state file next to the lock file").
FOMO_STATE_DIR = os.getenv('FOMO_STATE_DIR', FOMO_LOCK_DIR)
# FOMO_LOG_FILE: only ever quoted as a path -- by the failure email (D-14) and by
# check_unattended (a later plan) -- the runner itself writes to stdout/stderr and cron does
# the append-redirect (D-18).
FOMO_LOG_FILE = os.getenv('FOMO_LOG_FILE', '/var/log/fomo/unattended.log')

try:
    from fomo.local_settings import *  # noqa
except ImportError as exc:
    # Only the absence of local_settings.py itself is expected and safe to swallow -- an
    # ImportError raised INSIDE that module (a typo'd sibling import, a package missing from
    # this host's venv) must propagate, or the host silently reverts to every dev default
    # (committed SECRET_KEY, DEBUG=True, console EMAIL_BACKEND, empty facility api_keys) with
    # no error at all (WR-32, 36-REVIEW.md iteration 5).
    if exc.name != 'fomo.local_settings':
        raise

# `from fomo.local_settings import *` executes that module in its own namespace, so it can only
# ASSIGN new settings -- it cannot mutate ones already built above (FACILITIES['LCO']['api_key']
# = ... there raises NameError, which the ImportError guard does not catch). Secrets that belong
# inside an existing dict therefore arrive as flat names and are folded in here.
if 'LCO_API_KEY' in globals():
    # The presence guard above covers only the source name -- a local_settings.py that
    # replaces FACILITIES wholesale (the one thing it is documented to be able to do) can
    # legally omit 'SOAR', which is a FOMO-local addition, not part of a stock TOM
    # FACILITIES block. setdefault() makes the destination as tolerant as the source guard,
    # so a missing 'SOAR' key can no longer crash settings import with an uncaught KeyError
    # (WR-28, 36-REVIEW.md iteration 5). SOAR authenticates against the same LCO Observation
    # Portal (see the FACILITIES['SOAR'] entry above) -- if that ever changes, remove the
    # 'SOAR' entry from this loop (see IN-31, 36-REVIEW.md iteration 5).
    for _facility in ('LCO', 'SOAR'):
        FACILITIES.setdefault(_facility, {})['api_key'] = LCO_API_KEY  # noqa: F405
    # IN-37 (36-REVIEW.md): del the loop variable rather than leaving it bound in the
    # settings module's namespace after the loop -- harmless today (Django's Settings
    # only copies isupper() names off this module), but it left the module's final
    # namespace carrying a stray non-setting.
    del _facility
