# Generated by Django 5.2.14 on 2026-06-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_calendar', '0005_calendarevent_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventTelescopeLabel',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='telescope_label_meta', serialize=False, to='tom_calendar.calendarevent', verbose_name='Calendar event')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Whether the telescope label was live-verified against the LCO API')),
            ],
        ),
    ]
