# Generated by Django 5.2.15 on 2026-07-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0001_calendareventtelescopelabel'),
        ('solsys_code_observatory', '0002_observatory_timezone_seed'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_instrument', models.CharField(max_length=255, verbose_name='Telescope / instrument')),
                (
                    'site_raw',
                    models.CharField(blank=True, default='', max_length=255, verbose_name='Original site code text'),
                ),
                (
                    'site_needs_review',
                    models.BooleanField(
                        default=False,
                        verbose_name='Whether the site could not be automatically resolved and needs manual review',
                    ),
                ),
                ('obs_date', models.DateField(blank=True, null=True, verbose_name='Observation date')),
                ('ut_start', models.DateTimeField(blank=True, null=True, verbose_name='UT start time')),
                ('ut_end', models.DateTimeField(blank=True, null=True, verbose_name='UT end time')),
                (
                    'filters_bandpass',
                    models.CharField(blank=True, default='', max_length=255, verbose_name='Filter(s) / bandpass'),
                ),
                ('observation_details', models.TextField(blank=True, default='', verbose_name='Observation details')),
                ('weather', models.TextField(blank=True, default='', verbose_name='Weather conditions or forecast')),
                ('observation_outcome', models.TextField(blank=True, default='', verbose_name='Observation outcome')),
                ('publication_plans', models.TextField(blank=True, default='', verbose_name='Publication plans')),
                ('open_to_collaboration', models.BooleanField(default=False, verbose_name='Open to collaboration?')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Other comments')),
                (
                    'contact_person',
                    models.CharField(blank=True, default='', max_length=255, verbose_name='Contact person'),
                ),
                (
                    'contact_email',
                    models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact email'),
                ),
                (
                    'approval_status',
                    models.CharField(
                        choices=[
                            ('pending_review', 'Pending Review'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending_review',
                        max_length=20,
                        verbose_name='Approval status',
                    ),
                ),
                (
                    'run_status',
                    models.CharField(
                        choices=[
                            ('requested', 'Requested'),
                            ('planned', 'Planned'),
                            ('observed', 'Observed'),
                            ('reduced', 'Reduced'),
                            ('published', 'Published'),
                            ('cancelled', 'Cancelled'),
                            ('not_awarded', 'Not Awarded'),
                            ('weather_tech_failure', 'Weather/Technical Failure'),
                        ],
                        default='requested',
                        max_length=30,
                        verbose_name='Run status',
                    ),
                ),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='campaign_runs',
                        to='tom_targets.targetlist',
                        verbose_name='Campaign target list',
                    ),
                ),
                (
                    'site',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='campaign_runs',
                        to='solsys_code_observatory.observatory',
                        verbose_name='Resolved observing site',
                    ),
                ),
                (
                    'target',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='campaign_runs',
                        to='tom_targets.basetarget',
                        verbose_name='Observed target',
                    ),
                ),
            ],
        ),
    ]
