# Generated by Django 5.2.15 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0002_campaignrun'),
        ('solsys_code_observatory', '0002_observatory_timezone_seed'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.UniqueConstraint(
                fields=('campaign', 'telescope_instrument', 'ut_start'), name='unique_campaign_run_natural_key'
            ),
        ),
    ]
