# Generated by Django 5.2.15 on 2026-07-09, hand-edited per
# .planning/phases/19-window-schema-migration/19-RESEARCH.md Pattern 1 to insert the two
# RunPython data-migration steps (backfill + dedup) in the load-bearing position: after the
# new fields are added, before the old constraint/fields are removed, and before the two new
# partial constraints are added (Pitfall 3 -- the dedup must precede AddConstraint(tbd) or
# that step raises IntegrityError against real leftover duplicate rows). D-02: single
# combined, non-reversible migration.

import logging

from django.db import migrations, models
from django.db.models import F

logger = logging.getLogger(__name__)


def backfill_window_fields(apps, schema_editor):
    """SCHED-05: window_start=window_end=obs_date for every row (NULL stays NULL -> TBD)."""
    CampaignRun = apps.get_model('solsys_code', 'CampaignRun')
    CampaignRun.objects.all().update(window_start=F('obs_date'), window_end=F('obs_date'))


def dedupe_tbd_collisions(apps, schema_editor):
    """D-07/D-08: generic cleanup of (campaign, telescope_instrument, contact_person)
    collisions among window_start IS NULL rows -- keeps the lowest pk, deletes the rest,
    logs what was removed. Must run before the new TBD-branch UniqueConstraint is added
    below, or that AddConstraint would fail against real leftover-fixture duplicates.
    """
    CampaignRun = apps.get_model('solsys_code', 'CampaignRun')
    seen: dict[tuple, int] = {}
    # order_by('pk') is what makes "keep the lowest pk" correct: the first row seen for
    # a given key is always the lowest-pk one, so every later match is a dup to delete.
    for run in CampaignRun.objects.filter(window_start__isnull=True).order_by('pk'):
        key = (run.campaign_id, run.telescope_instrument, run.contact_person)
        if key in seen:
            logger.warning(
                'Deleting duplicate TBD CampaignRun pk=%s (kept pk=%s) for '
                'campaign=%s telescope_instrument=%r contact_person=%r',
                run.pk,
                seen[key],
                run.campaign_id,
                run.telescope_instrument,
                run.contact_person,
            )
            run.delete()
        else:
            seen[key] = run.pk


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0003_campaignrun_natural_key_unique_constraint'),
        ('solsys_code_observatory', '0002_observatory_timezone_seed'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        # 1-2: new nullable fields, added first so RunPython below can populate them.
        migrations.AddField(
            model_name='campaignrun',
            name='window_start',
            field=models.DateField(blank=True, null=True, verbose_name='Observing window start'),
        ),
        migrations.AddField(
            model_name='campaignrun',
            name='window_end',
            field=models.DateField(blank=True, null=True, verbose_name='Observing window end'),
        ),
        # 3-4: data migration, in this order (backfill before dedup -- dedup keys on
        # window_start IS NULL, which is only meaningful after backfill runs).
        migrations.RunPython(backfill_window_fields, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(dedupe_tbd_collisions, reverse_code=migrations.RunPython.noop),
        # 5: old constraint removed BEFORE the fields it references are removed.
        migrations.RemoveConstraint(
            model_name='campaignrun',
            name='unique_campaign_run_natural_key',
        ),
        # 6: old fields dropped (D-01 hard cutover).
        migrations.RemoveField(
            model_name='campaignrun',
            name='obs_date',
        ),
        migrations.RemoveField(
            model_name='campaignrun',
            name='ut_end',
        ),
        migrations.RemoveField(
            model_name='campaignrun',
            name='ut_start',
        ),
        # 7-8: new partial constraints -- resolved-window branch keyed on all four fields;
        # TBD branch keyed on (campaign, telescope_instrument, contact_person) only.
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(('window_start__isnull', False)),
                fields=('campaign', 'telescope_instrument', 'window_start', 'window_end'),
                name='unique_campaign_run_resolved_window',
            ),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(('window_start__isnull', True)),
                fields=('campaign', 'telescope_instrument', 'contact_person'),
                name='unique_campaign_run_tbd_natural_key',
            ),
        ),
    ]
