# Generated by Django 5.2.15 on 2026-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0004_campaignrun_window_schema'),
        ('solsys_code_observatory', '0002_observatory_timezone_seed'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('window_end__isnull', True), ('window_start__isnull', True)),
                    models.Q(('window_end__isnull', False), ('window_start__isnull', False)),
                    _connector='OR',
                ),
                name='campaign_run_window_start_end_null_together',
            ),
        ),
    ]
