# Generated by Django 5.2.15 on 2026-07-10 07:24, hand-edited per
# .planning/phases/19-window-schema-migration/19-REVIEW.md WR-02 to add a defensive
# RunPython cleanup step ahead of the AddConstraint below, mirroring 0004's own CR-01
# precedent for the same class of risk (adding a constraint against data that may not
# actually satisfy it yet raises an unhandled IntegrityError with no recovery path).

import logging

from django.db import migrations, models
from django.db.models import Q

logger = logging.getLogger(__name__)


def normalize_mismatched_window_pairs(apps, schema_editor):
    """WR-02: normalize any single-sided window_start/window_end pair to fully-TBD
    (both NULL) before the campaign_run_window_start_end_null_together CheckConstraint
    is added below.

    In the current codebase this is a no-op: 0004's backfill_window_fields sets both
    fields from the same source column (F('obs_date')), and no write path
    (CampaignRunSubmissionView, import_campaign_csv) ever sets them independently, so
    the invariant already holds by the time this migration runs in the same deploy as
    0004. This step exists purely as a safety net for the case where 0004 and 0005 are
    applied as separate deploys (e.g. a squashed or backported migration set) and an
    out-of-band write (a fixture load, a data-migration bug elsewhere, a direct DB
    edit) creates a mismatched-pair row in the gap between them.
    """
    CampaignRun = apps.get_model('solsys_code', 'CampaignRun')
    mismatched = CampaignRun.objects.filter(
        Q(window_start__isnull=True, window_end__isnull=False)
        | Q(window_start__isnull=False, window_end__isnull=True)
    ).order_by('pk')
    for run in mismatched:
        logger.warning(
            'Normalizing mismatched window pair for CampaignRun pk=%s '
            '(window_start=%s, window_end=%s) to fully-TBD before adding '
            'campaign_run_window_start_end_null_together constraint',
            run.pk,
            run.window_start,
            run.window_end,
        )
        run.window_start = None
        run.window_end = None
        run.save(update_fields=['window_start', 'window_end'])


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0004_campaignrun_window_schema'),
        ('solsys_code_observatory', '0002_observatory_timezone_seed'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.RunPython(normalize_mismatched_window_pairs, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('window_end__isnull', True), ('window_start__isnull', True)),
                    models.Q(('window_end__isnull', False), ('window_start__isnull', False)),
                    _connector='OR',
                ),
                name='campaign_run_window_start_end_null_together',
            ),
        ),
    ]
