# Generated by Django 5.2.15 on 2026-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0005_campaignrun_campaign_run_window_start_end_null_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrun',
            name='original_obs_date_raw',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='Original Obs. Date text (TBD rows only)'
            ),
        ),
        migrations.AddField(
            model_name='campaignrun',
            name='window_needs_review',
            field=models.BooleanField(
                default=False,
                verbose_name='Whether the observing window could not be automatically resolved and needs manual review',
            ),
        ),
    ]
