# Generated by Django 5.2.15 on 2026-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0006_campaignrun_original_obs_date_raw_and_window_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrun',
            name='contact_public_opt_in',
            field=models.BooleanField(default=False, verbose_name='Show contact info publicly?'),
        ),
    ]
