# Generated by Django 5.2.13 on 2026-08-01 15:36
#
# Header comment added by hand (28-RESEARCH.md Assumption A4 / 28-PATTERNS.md): the two new
# dismissal models (CalendarEventDismissal, ObservationRecordDismissal) and the two new
# CalendarEventMeta audit fields (confirmed_by/confirmed_at, D-12) ship together in this one
# migration rather than split the way 0008/0009 split a rename from a field-add. Unlike that
# rename, all four operations here are purely additive, none touches an existing table's
# data, and none carries a regression risk that could be confused for another's -- there is
# no reason to force four separate deploy/rollback boundaries onto four independent adds.
# The operations below are autodetected by `makemigrations`, not hand-authored.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0012_unflag_class_wide_campaignrun_site_review'),
        ('tom_calendar', '0005_calendarevent_instrument'),
        ('tom_observations', '0016_alter_facility_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareventmeta',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at'),
        ),
        migrations.AddField(
            model_name='calendareventmeta',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_calendar_event_metas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by'),
        ),
        migrations.CreateModel(
            name='CalendarEventDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dismissed at')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Why this candidate was rejected')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_calendar_event_attributions', to=settings.AUTH_USER_MODEL, verbose_name='Dismissed by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_dismissals', to='tom_calendar.calendarevent', verbose_name='Calendar event')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_dismissals', to='solsys_code.campaignrun', verbose_name='Campaign run')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'run'), name='unique_calendar_event_dismissal_pair')],
            },
        ),
        migrations.CreateModel(
            name='ObservationRecordDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dismissed at')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Why this candidate was rejected')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_observation_record_attributions', to=settings.AUTH_USER_MODEL, verbose_name='Dismissed by')),
                ('observation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_dismissals', to='tom_observations.observationrecord', verbose_name='Observation record')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_record_dismissals', to='solsys_code.campaignrun', verbose_name='Campaign run')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('observation_record', 'run'), name='unique_observation_record_dismissal_pair')],
            },
        ),
    ]
