# Generated by Django 5.2.13 on 2026-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0013_attribution_dismissals_and_calendar_event_meta_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrun',
            name='source',
            field=models.CharField(
                choices=[
                    ('web', 'Web submission'),
                    ('classical_file', 'Classical run file'),
                    ('lco_queue', 'LCO queue'),
                    ('gemini_queue', 'Gemini queue'),
                    ('eso_queue', 'ESO queue'),
                    ('csv_import', 'CSV import'),
                    ('legacy', 'Legacy (pre-v2.2)'),
                ],
                default='legacy',
                max_length=20,
                verbose_name='Ingest source',
            ),
        ),
    ]
