# Generated by Django 5.2.17 on 2026-09-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0014_alter_campaignrun_source'),
        ('solsys_code_observatory', '0003_backfill_observatory_timezone'),
        ('tom_targets', '0031_basetarget_shared_by_basetarget_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrun',
            name='source_identifier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Write-time identity key'),
        ),
        migrations.AlterField(
            model_name='campaignrun',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_runs', to='tom_targets.targetlist', verbose_name='Campaign target list'),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.UniqueConstraint(condition=models.Q(('source_identifier__isnull', False)), fields=('source_identifier',), name='unique_campaign_run_source_identifier'),
        ),
    ]
