# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code', '0015_campaignrun_nullable_campaign_and_source_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrun',
            name='source',
            field=models.CharField(
                choices=[
                    ('web', 'Web submission'),
                    ('classical_file', 'Classical run file'),
                    ('lco_queue', 'LCO queue'),
                    ('soar_queue', 'SOAR queue'),
                    ('gemini_queue', 'Gemini queue'),
                    ('eso_queue', 'ESO queue'),
                    ('csv_import', 'CSV import'),
                    ('legacy', 'Legacy (pre-v2.2)'),
                ],
                default='legacy',
                max_length=20,
                verbose_name='Ingest source',
            ),
        ),
    ]
