# Generated by Django 5.2.17 on 2026-09-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0016_alter_campaignrun_source_soar_queue'),
        ('tom_observations', '0016_alter_facility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareventmeta',
            name='observation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event_metas', to='tom_observations.observationgroup', verbose_name='Observation group'),
        ),
        migrations.AddField(
            model_name='calendareventmeta',
            name='observation_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event_meta', to='tom_observations.observationrecord', verbose_name='Observation record'),
        ),
        migrations.AlterField(
            model_name='calendareventmeta',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event_metas', to='solsys_code.campaignrun', verbose_name='Attributed campaign run'),
        ),
    ]
