# Generated by Django 5.2.17 on 2026-09-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0017_calendareventmeta_observation_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrun',
            name='night_end_utc',
            field=models.TimeField(blank=True, null=True, verbose_name='Observing night end (UTC time of day)'),
        ),
        migrations.AddField(
            model_name='campaignrun',
            name='night_start_utc',
            field=models.TimeField(blank=True, null=True, verbose_name='Observing night start (UTC time of day)'),
        ),
    ]
