# Generated by Django 5.2.17 on 2026-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0018_campaignrun_night_window_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareventmeta',
            name='minted_sub_night_window',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Minted sub-night window'),
        ),
    ]
