# Generated by Django 5.2.17 on 2026-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0019_calendareventmeta_minted_sub_night_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendareventmeta',
            name='minted_sub_night_window',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Minted sub-night window'),
        ),
    ]
