# Generated by Django 5.2.17 on 2026-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0020_alter_calendareventmeta_minted_sub_night_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendareventmeta',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Setting this False permanently prevents the allocation projector from correcting the boundaries of this night: an automated re-mint is declined and reported under remint_declined. It does not prevent the night being retired when a linked observation places a block on it. See the runbook section on remint_declined.', verbose_name='Whether the telescope label was live-verified against the LCO API (unchecking also vetoes an automated re-mint)'),
        ),
        migrations.AlterField(
            model_name='calendareventmeta',
            name='minted_sub_night_window',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Minted sub-night window'),
        ),
    ]
