# Generated by Django 5.2.17 on 2026-09-17 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0021_alter_calendareventmeta_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(max_length=100, unique=True, verbose_name='Proposal code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('target_list_name', models.CharField(blank=True, default='', max_length=200, verbose_name='TargetList name override')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last swept at')),
                ('last_run_summary', models.TextField(blank=True, default='', verbose_name='Last sweep summary')),
                ('attributed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watched_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Attribute records to')),
            ],
            options={
                'ordering': ['proposal_code'],
            },
        ),
    ]
