# Generated by Django 5.2.17 on 2026-09-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0022_watchedproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrun',
            name='proposal_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Proposal code'),
        ),
        migrations.CreateModel(
            name='ProposalTimeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(max_length=100, verbose_name='Proposal code')),
                ('semester', models.CharField(blank=True, default='', max_length=32, verbose_name='Semester')),
                ('instrument_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Instrument type')),
                ('allocation_type', models.CharField(max_length=16, verbose_name='Allocation type')),
                ('allocated_hours', models.FloatField(default=0.0, verbose_name='Allocated hours')),
                ('used_hours', models.FloatField(default=0.0, verbose_name='Used hours')),
                ('fetched_at', models.DateTimeField(verbose_name='Fetched at')),
            ],
            options={
                'ordering': ['proposal_code', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('proposal_code', 'semester', 'instrument_type', 'allocation_type'), name='unique_proposal_time_allocation_key')],
            },
        ),
    ]
