# Generated by Django 5.2.17 on 2026-10-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0023_proposal_time_allocation_and_campaignrun_proposal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrunobservation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_campaign_run_observations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by'),
        ),
    ]
