# Generated by Django 5.2.17 on 2026-10-03 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsys_code', '0024_campaignrunobservation_confirmed_by_protect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendareventmeta',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_calendar_event_metas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by'),
        ),
    ]
