#!/usr/bin/env bash
# Install FOMO as a systemd *user* service (gunicorn), so it starts at boot and restarts if it dies.
#
# Usage, from the FOMO virtualenv after `pip install -e '.[deploy]'`:
#   deploy/install_service.sh [BIND]          # BIND defaults to "$(hostname -f):6729"
#
# Afterwards:
#   systemctl --user start|stop|restart|status fomo
#   journalctl --user -u fomo -f
# Optional extra environment (e.g. TNS_*/FINK_* read by settings.py) goes in ~/.config/fomo/fomo.env
set -o nounset -o errexit -o pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
VENV_DIR=${VIRTUAL_ENV:-${CONDA_PREFIX:-}}
BIND=${1:-$(hostname -f):6729}
UNIT_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
UNIT_FILE=$UNIT_DIR/fomo.service

if [ -z "$VENV_DIR" ]; then
    echo "Activate the FOMO virtualenv (or conda env) first." >&2
    exit 1
fi
if [ ! -x "$VENV_DIR/bin/gunicorn" ]; then
    echo "gunicorn not found in $VENV_DIR; run: pip install -e '.[deploy]'" >&2
    exit 1
fi

mkdir -p "$UNIT_DIR"
cat > "$UNIT_FILE" <<EOF
# Generated by $REPO_DIR/deploy/install_service.sh -- re-run that script rather than editing this file.
[Unit]
Description=FOMO TOM (gunicorn on $BIND)
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WorkingDirectory=$REPO_DIR
Environment=FOMO_BIND=$BIND
EnvironmentFile=-%h/.config/fomo/fomo.env
ExecStartPre=$VENV_DIR/bin/python manage.py collectstatic --noinput --verbosity 0
ExecStart=$VENV_DIR/bin/gunicorn --config deploy/gunicorn.conf.py
ExecReload=/bin/kill -s HUP \$MAINPID
KillMode=mixed
TimeoutStopSec=150
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable fomo.service
echo "Installed and enabled $UNIT_FILE (bind: $BIND)."
echo "Start it with: systemctl --user start fomo"

if [ "$(loginctl show-user "$USER" --property=Linger --value 2>/dev/null)" != "yes" ]; then
    echo
    echo "NOTE: lingering is off for $USER, so the service only runs while you are logged in."
    echo "To start it at boot without a login, run once:  sudo loginctl enable-linger $USER"
fi
