# LCO Backfill Demo (backfill_lco_observations)

This notebook demonstrates `solsys_code/management/commands/backfill_lco_observations.py`,
the campaign-agnostic backfill command that creates or updates `ObservationRecord`s (and,
where needed, non-sidereal `Target`s and `ObservationGroup`s), and collects every `Target`
it touches into a `TargetList`, from the LCO Observation Portal's "Get All RequestGroups"
API.

It exists alongside `backfill_lco_observation_records` (see
`backfill_lco_observation_records_demo` / the runbook for that command) but has a different
contract: no campaign is required, an already-existing `ObservationRecord` is updated in
place instead of skipped, an unmatched target is built as a non-sidereal `Target` from its
own orbital elements (never a sidereal field target), and a multi-request `RequestGroup` is
linked into a reusable `ObservationGroup`.

It demonstrates, in order:

- A `--dry-run` pass over a hand-built two-request `RequestGroup` payload, showing the
  summary report with nothing written to the database
- A real pass creating both `ObservationRecord`s, the non-sidereal demo `Target`, the
  `ObservationGroup` linking them, and the `TargetList` collecting the touched target
- A second real pass over an advanced-state, narrowed-schedule payload, printing the
  before/after row for the request whose state and observed block moved, and confirming the
  second request (whose data is unchanged) is left untouched -- both the in-place update and
  the no-churn `unchanged` count are visible
- Discovery keeping the observed-site keys (`observed_site`, `observed_telescope`,
  `observed_enclosure`) that the projector sweep stores in `parameters`: a re-run over
  unchanged portal data leaves them and counts the record `unchanged`, and a re-run that
  really moves a request window updates `start`/`end` while still keeping them
- Discovery skipping the live observed-block lookup for a record that is already finished at
  the same portal state: a re-run over finished records makes zero lookups and reports them
  under `fallback lookups skipped`, while a brand-new request is still counted under
  `fallback lookups needed`
- The sweep linking exact matches to a run by itself (system links): one record linked by target,
  one by the campaign fallback, one left in the attribution queue as ambiguous, the `--dry-run`
  would-link lines, the `System (exact match)` label, and a second pass that links nothing new
- A block that started and was aborted after taking data: an ordinary sweep leaves a legacy
  record that has no times alone (no lookup), and one `--recheck-unscheduled` sweep gives it
  that block's times and retires exactly that night's allocation entry, while a request that
  never got a block keeps its night
- A cleanup cell deleting every row the notebook created, including the `TargetList`, so it
  is safely re-runnable

This notebook lives in `pre_executed/` because it is **DB-dependent** (it creates real
`Target`/`ObservationRecord`/`ObservationGroup`/`TargetList` rows in a throwaway scratch
database that the setup cell builds and migrates, never the developer database)
and makes no live network call -- the LCO portal's `GET /api/requestgroups/` response and the
observed-block lookup (`FomoLCOFacility.get_observation_status()`, TOM's two portal calls with FOMO's
block choice) are both mocked with a small, hand-built payload, so a reader can see exactly what the portal's response shape looks like.

## Django setup

Standard boilerplate to make `src.fomo.settings` importable from this notebook's location
(`docs/notebooks/pre_executed/` -- three levels under the repo root, so `parents[2]` gives
the repo root) and to allow synchronous ORM calls inside Jupyter's async event loop.

Before `django.setup()` runs, the setup cell also points `FOMO_DATABASE_PATH` at a brand
new scratch database file, then migrates it from empty. Every row this notebook creates lives
there and is torn down at the end. The scratch database is fresh rather than a copy of the
developer database on purpose: a copy would carry along whatever watched proposals that host
has active, and the bare-invocation section below sweeps every active watched row.


In [1]:
import os
import sys
import tempfile
from pathlib import Path

import django

# Ensure the repo root is on sys.path so `src.fomo.settings` is importable
# when this notebook is executed from docs/notebooks/pre_executed/.
# NOTE: parents[2] is correct only when the Jupyter kernel CWD is
# docs/notebooks/pre_executed/. Start Jupyter from that directory, or
# adjust the index if you launch from the repo root.
repo_root_path = Path.cwd().resolve().parents[2]
if not (repo_root_path / 'manage.py').exists():
    raise RuntimeError(f'No manage.py at {repo_root_path}; run Jupyter from docs/notebooks/pre_executed/')
repo_root = str(repo_root_path)
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'src.fomo.settings')

# Jupyter's ipykernel runs inside an asyncio event loop, but Django's ORM is
# sync-only by default and refuses to run there; this opts back in.
os.environ.setdefault('DJANGO_ALLOW_ASYNC_UNSAFE', 'true')

# Route the whole notebook to a fresh, throwaway scratch database BEFORE django.setup() --
# that call is what materialises DATABASES, so the variable must already be exported.
# Deliberately NOT a copy of src/fomo_db.sqlite3 (unlike reconcile_campaign_runs_demo): a copy
# would bring along the host's active watched proposals, which the bare-invocation cell below
# would then sweep through a mock that only knows the demo codes; the live file may also be
# mid-write by the unattended runner; and this demo creates every row it needs itself.
# A plain assignment, never setdefault, so an inherited value can never point at a real database.
scratch_db_dir = Path(tempfile.mkdtemp(prefix='fomo-notebook-db-'))
scratch_db_path = scratch_db_dir / 'fomo_db.sqlite3'
os.environ['FOMO_DATABASE_PATH'] = str(scratch_db_path)

django.setup()

from django.conf import settings as django_settings

resolved_db_name = django_settings.DATABASES['default']['NAME']
assert resolved_db_name == str(scratch_db_path), (
    'This notebook must never write to the developer or live database -- resolved DB '
    f'{resolved_db_name!r} is not the scratch database {str(scratch_db_path)!r}.'
)

# Build the schema from empty.
from django.core.management import call_command as _call_command

_call_command('migrate', verbosity=0)

print(f'Resolved database: {resolved_db_name!r} (fresh scratch database, migrated from empty)')

No Profile found for AnonymousUser. Creating Profile.


Resolved database: '/tmp/fomo-notebook-db-56d061pr/fomo_db.sqlite3' (fresh scratch database, migrated from empty)


## Build a hand-built RequestGroup payload

The fixture below is a single `RequestGroup` (id `900100`) carrying **two** requests, so the
same run also demonstrates `ObservationGroup` linking (D-D). Each request's target is a
complete `ORBITAL_ELEMENTS` dict using the LCO/OCS wire-key spelling (`orbinc`,
`longascnode`, `argofperih`, `meandist`, `meananom`, `dailymot`/`eccentricity`, `epochofel`)
that `_extract_orbital_elements()` maps onto TOM `Target` field names (D-E). Neither request
carries an embedded `'observations'` block, so both go through the D-B live fallback
(`FomoLCOFacility.get_observation_status()` -- TOM's two portal calls with FOMO's block choice), which is mocked below rather than the embedded-block
path -- the more realistic shape for a real portal response, since the RequestGroups listing
endpoint does not itself embed per-request observation blocks.


In [2]:
DEMO_PROPOSAL = 'BACKFILL-DEMO-2026A'
DEMO_TARGET_NAME = 'Backfill Demo Object'
DEMO_GROUP_NAME_FRAGMENT = 'Backfill Demo Group'


def _orbital_elements():
    return {
        'scheme': 'MPC_MINOR_PLANET',
        'orbinc': 5.2,
        'longascnode': 80.1,
        'argofperih': 300.4,
        'meandist': 2.2,
        'meananom': 12.3,
        'eccentricity': 0.15,
        'epochofel': 58600.0,
    }


def _configuration(target_name):
    return {
        'type': 'EXPOSE',
        'instrument_type': '1M0-SCICAM-SINISTRO',
        'instrument_configs': [{'exposure_time': 30.0, 'exposure_count': 1}],
        'target': {'name': target_name, 'type': 'ORBITAL_ELEMENTS', **_orbital_elements()},
    }


def _request(request_id, state):
    return {
        'id': request_id,
        'state': state,
        'windows': [{'start': '2026-07-01T00:00:00', 'end': '2026-07-02T00:00:00'}],
        'configurations': [_configuration(DEMO_TARGET_NAME)],
    }


def _request_group(requests):
    return {
        'id': 900100,
        'name': DEMO_GROUP_NAME_FRAGMENT,
        'proposal': DEMO_PROPOSAL,
        'state': 'PENDING',
        'created': '2026-07-01T00:00:00Z',
        'requests': requests,
    }


first_pass_request_group = _request_group([_request(900101, state='PENDING'), _request(900102, state='COMPLETED')])
print('Requests in demo RequestGroup:', [r['id'] for r in first_pass_request_group['requests']])

Requests in demo RequestGroup: [900101, 900102]


## Mocking helpers

No live network call is made anywhere in this notebook. `make_request` (the paging call
site) is patched to return the fixture payload above; `FomoLCOFacility.get_observation_status`
(the D-B fallback: TOM's two portal calls with FOMO's block choice) is patched with a per-observation-id schedule lookup table, so the two
requests can carry independently evolving observed-block times across the two passes below.


In [3]:
import io
from unittest.mock import MagicMock, patch

from django.core.management import call_command

FIRST_PASS_SCHEDULE = {
    '900101': {'scheduled_start': '2026-07-01T00:10:00+00:00', 'scheduled_end': '2026-07-01T00:20:00+00:00'},
    '900102': {'scheduled_start': '2026-07-05T00:10:00+00:00', 'scheduled_end': '2026-07-05T00:20:00+00:00'},
}


def _page_response(results):
    response = MagicMock()
    response.json.return_value = {'count': len(results), 'next': None, 'previous': None, 'results': results}
    return response


def _status_lookup(schedule_table):
    def _get_observation_status(observation_id):
        times = schedule_table[observation_id]
        return {'state': 'na (unused -- status comes from the request payload itself)', **times}

    return _get_observation_status

## `--dry-run` pass: report only, nothing written

With `--dry-run`, the command still resolves every decision (target match/build, schedule)
but performs no `save()`/`create()`/`add()` -- and the D-B live fallback lookup is skipped
entirely, so `get_observation_status` is never called in this cell.

The dry-run counts below equal what the following real pass over the same payload will
report -- `targets would create: 1` because both requests share `DEMO_TARGET_NAME`, a
target FOMO doesn't have yet, and the same-invocation de-dup counts it once, matching how
a real run saves the target on the first request and matches it on the second. The two
schedule-path counters, `embedded blocks` and `fallback lookups needed`, reveal which
schedule path the portal actually exercises for this payload without any extra HTTP call
beyond the initial listing -- neither request here carries an embedded `observations`
block, so both fall back, giving `embedded blocks: 0, fallback lookups needed: 2`. `fallback lookups skipped: 0` appears
here too, because nothing exists yet and so nothing can be skipped. The one
caveat: a request needing the live fallback lookup has its schedule compared by a real run
but not by a dry run (the lookup that would produce a schedule to compare is skipped), so
such a record can be reported `unchanged` by a dry run when only its schedule times would
actually move.

The dry run also reports which `TargetList` it would create or reuse and how many targets
it would add -- `target list: would create 'BACKFILL-DEMO-2026A_targets', targets would add
to list: 1` -- without writing the list itself.


In [4]:
from tom_observations.models import ObservationGroup, ObservationRecord
from tom_targets.models import Target, TargetList

dry_run_stdout, dry_run_stderr = io.StringIO(), io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([first_pass_request_group]),
    ) as mock_make_request,
    patch('solsys_code.observation_blocks.FomoLCOFacility.get_observation_status') as mock_get_observation_status,
):
    call_command(
        'backfill_lco_observations',
        '--proposal',
        DEMO_PROPOSAL,
        '--dry-run',
        stdout=dry_run_stdout,
        stderr=dry_run_stderr,
    )

print('stdout:', dry_run_stdout.getvalue())
if dry_run_stderr.getvalue():
    print('stderr:', dry_run_stderr.getvalue())

print('get_observation_status called during --dry-run:', mock_get_observation_status.called)
print(
    'ObservationRecords written:',
    ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900101', '900102']).count(),
)
print('Demo Target written:', Target.objects.filter(name=DEMO_TARGET_NAME).exists())
print(
    'Demo ObservationGroup written:',
    ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT).exists(),
)
print('Demo TargetList written:', TargetList.objects.filter(name=f'{DEMO_PROPOSAL}_targets').exists())
if not TargetList.objects.filter(name=f'{DEMO_PROPOSAL}_targets').exists():
    print(f"PASS: dry run wrote no TargetList named '{DEMO_PROPOSAL}_targets'")

stdout: Would create target 'Backfill Demo Object'; would create ObservationRecord observation_id='900101' status='PENDING'.
Would reuse target 'Backfill Demo Object'; would create ObservationRecord observation_id='900102' status='COMPLETED'.
Would create ObservationGroup 'Backfill Demo Group (900100)'.
requestgroups seen: 1, would create: 2, would update: 0, unchanged: 0, skipped: 0, targets would create: 1, groups would create: 1, groups would reuse: 0, embedded blocks: 0, fallback lookups needed: 2, fallback lookups skipped: 0, block lookups failed: n/a (dry-run), target list: would create 'BACKFILL-DEMO-2026A_targets', targets would add to list: 1, would link: 0, links skipped: 0

get_observation_status called during --dry-run: False
ObservationRecords written: 0
Demo Target written: False
Demo ObservationGroup written: False
Demo TargetList written: False
PASS: dry run wrote no TargetList named 'BACKFILL-DEMO-2026A_targets'


## Real pass: create the records, the non-sidereal target, and the group

The same payload, without `--dry-run`. `DEMO_TARGET_NAME` isn't a Target FOMO already knows
about, so it gets built as a non-sidereal `Target` from the orbital elements in the fixture
above -- never a sidereal one (D-G). Because the `RequestGroup` carries two requests, the
command also creates one `ObservationGroup` linking both resulting records (D-D).


In [5]:
real_stdout, real_stderr = io.StringIO(), io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([first_pass_request_group]),
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(FIRST_PASS_SCHEDULE),
    ),
):
    call_command('backfill_lco_observations', '--proposal', DEMO_PROPOSAL, stdout=real_stdout, stderr=real_stderr)

print('stdout:', real_stdout.getvalue())
if real_stderr.getvalue():
    print('stderr:', real_stderr.getvalue())

Target post save hook: Backfill Demo Object created: True


Observation change state hook: Backfill Demo Object @ LCO from None to PENDING


Observation change state hook: Backfill Demo Object @ LCO from None to COMPLETED


stdout: requestgroups seen: 1, created: 2, updated: 0, unchanged: 0, skipped: 0, targets created: 1, groups created: 1, groups reused: 0, embedded blocks: 0, fallback lookups needed: 2, fallback lookups skipped: 0, block lookups failed: 0, target list: created 'BACKFILL-DEMO-2026A_targets', targets added to list: 1, system links: 0, links skipped: 0



## Inspect what the real pass created, including the TargetList


In [6]:
demo_target = Target.objects.get(name=DEMO_TARGET_NAME)
print('target type       :', demo_target.type)
print('target scheme      :', demo_target.scheme)
print('target inclination :', demo_target.inclination)

record_101 = ObservationRecord.objects.get(facility='LCO', observation_id='900101')
record_102 = ObservationRecord.objects.get(facility='LCO', observation_id='900102')
print('900101 status/start/end:', record_101.status, record_101.scheduled_start, record_101.scheduled_end)
print('900102 status/start/end:', record_102.status, record_102.scheduled_start, record_102.scheduled_end)

demo_group = ObservationGroup.objects.get(name__startswith=DEMO_GROUP_NAME_FRAGMENT)
print('group name         :', demo_group.name)
print('group record ids   :', sorted(r.observation_id for r in demo_group.observation_records.all()))

demo_target_list = TargetList.objects.get(name=f'{DEMO_PROPOSAL}_targets')
print('target list name   :', demo_target_list.name)
print('target list members:', sorted(t.name for t in demo_target_list.targets.all()))

if demo_target.type == Target.NON_SIDEREAL and not Target.objects.filter(type=Target.SIDEREAL).exists():
    print('PASS: demo target is non-sidereal, and no sidereal target exists anywhere')

target type       : NON_SIDEREAL
target scheme      : MPC_MINOR_PLANET
target inclination : 5.2
900101 status/start/end: PENDING 2026-07-01 00:10:00+00:00 2026-07-01 00:20:00+00:00
900102 status/start/end: COMPLETED 2026-07-05 00:10:00+00:00 2026-07-05 00:20:00+00:00
group name         : Backfill Demo Group (900100)
group record ids   : ['900101', '900102']
target list name   : BACKFILL-DEMO-2026A_targets
target list members: ['Backfill Demo Object']
PASS: demo target is non-sidereal, and no sidereal target exists anywhere


## Second real pass: an advanced state and a narrowed observed block

Request `900101` advances from `PENDING` to `COMPLETED`, and its mocked observed block
narrows (`00:10-00:20` -> `00:15-00:18`) -- both are picked up by the second pass, updating
the existing `ObservationRecord` in place rather than creating a second one. Request
`900102`'s state and schedule are unchanged, so its row is left untouched (`modified`
timestamp unchanged) and the summary line counts it under `unchanged`, not `updated`.

`900102` is already `COMPLETED` and the portal still says `COMPLETED`, so its live
observed-block lookup is skipped: the summary reads `fallback lookups needed: 1, fallback
lookups skipped: 1`, because `900101`, whose state changed, is still looked up.


In [7]:
before_status = record_101.status
before_start = record_101.scheduled_start
before_end = record_101.scheduled_end
before_modified_102 = record_102.modified

second_pass_request_group = _request_group([_request(900101, state='COMPLETED'), _request(900102, state='COMPLETED')])

SECOND_PASS_SCHEDULE = {
    '900101': {'scheduled_start': '2026-07-01T00:15:00+00:00', 'scheduled_end': '2026-07-01T00:18:00+00:00'},
    '900102': FIRST_PASS_SCHEDULE['900102'],  # unchanged -- proves the no-churn path
}

second_stdout, second_stderr = io.StringIO(), io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([second_pass_request_group]),
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(SECOND_PASS_SCHEDULE),
    ),
):
    call_command('backfill_lco_observations', '--proposal', DEMO_PROPOSAL, stdout=second_stdout, stderr=second_stderr)

print('stdout:', second_stdout.getvalue())

record_101.refresh_from_db()
record_102.refresh_from_db()

print('900101 before -> after')
print('  status:', before_status, '->', record_101.status)
print('  start :', before_start, '->', record_101.scheduled_start)
print('  end   :', before_end, '->', record_101.scheduled_end)
print()
print('900102 modified timestamp unchanged:', record_102.modified == before_modified_102)

if record_101.status == 'COMPLETED' and record_101.scheduled_start.isoformat() == '2026-07-01T00:15:00+00:00':
    print('PASS: 900101 updated in place (no second row created)')
if record_102.modified == before_modified_102:
    print('PASS: 900102 left unchanged (no-churn re-run)')
print(
    'records still exactly 2:',
    ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900101', '900102']).count() == 2,
)
print(
    'groups still exactly 1:', ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT).count() == 1
)

Observation change state hook: Backfill Demo Object @ LCO from PENDING to COMPLETED


stdout: requestgroups seen: 1, created: 0, updated: 1, unchanged: 1, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 1, fallback lookups skipped: 1, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-2026A_targets', targets added to list: 1, system links: 0, links skipped: 0

900101 before -> after
  status: PENDING -> COMPLETED
  start : 2026-07-01 00:10:00+00:00 -> 2026-07-01 00:15:00+00:00
  end   : 2026-07-01 00:20:00+00:00 -> 2026-07-01 00:18:00+00:00

900102 modified timestamp unchanged: True
PASS: 900101 updated in place (no second row created)
PASS: 900102 left unchanged (no-churn re-run)
records still exactly 2: True
groups still exactly 1: True


## Discovery keeps the sweep's observed-site keys

The projector sweep's one-time observed-site lookup stores `observed_site`,
`observed_telescope` and `observed_enclosure` in each record's `parameters`, and treats their
presence as "already looked up". Discovery rebuilds `parameters` from the portal with only
`proposal`, `instrument_type`, `start` and `end`, and now carries those three keys forward.

Before this fix, every unattended tick counted each tagged record as `updated` and erased the
keys. The post_save trigger then re-drew the record's calendar event with the coarse
telescope token, and the next sweep repeated one live portal lookup per record.

The cells below tag both demo records exactly as the sweep does (`save(update_fields=['parameters'])`),
then re-run discovery over unchanged portal data (dry run and real), and finally over a
payload where request 900101's window has moved. Discovery still refreshes `start`/`end` when
the portal really changes, and the three keys survive that update too.

In [8]:
from solsys_code.calendar_utils import OBSERVED_SITE_PARAMETER_KEYS

TAGGED = {
    '900101': dict(zip(OBSERVED_SITE_PARAMETER_KEYS, ('elp', '1m0a', 'doma'))),
    '900102': dict(zip(OBSERVED_SITE_PARAMETER_KEYS, ('lsc', '1m0a', 'domb'))),
}
for record in (record_101, record_102):
    record.parameters.update(TAGGED[record.observation_id])
    record.save(update_fields=['parameters'])  # the same write resolve_observed_site() makes
# update_fields=['parameters'] does not write `modified`, so reload before capturing it.
record_101.refresh_from_db()
record_102.refresh_from_db()
modified_before = {'900101': record_101.modified, '900102': record_102.modified}

# Dry run over the unchanged payload.
keep_dry_stdout = io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([second_pass_request_group]),
    ),
    patch('solsys_code.observation_blocks.FomoLCOFacility.get_observation_status') as _dry_status,
):
    call_command(
        'backfill_lco_observations',
        '--proposal',
        DEMO_PROPOSAL,
        '--dry-run',
        stdout=keep_dry_stdout,
        stderr=io.StringIO(),
    )
print('dry-run stdout:', keep_dry_stdout.getvalue())

# Real run over the same, unchanged payload.
keep_real_stdout = io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([second_pass_request_group]),
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(SECOND_PASS_SCHEDULE),
    ),
):
    call_command(
        'backfill_lco_observations', '--proposal', DEMO_PROPOSAL, stdout=keep_real_stdout, stderr=io.StringIO()
    )
print('real-run stdout:', keep_real_stdout.getvalue())

record_101.refresh_from_db()
record_102.refresh_from_db()
print('900101 parameters:', record_101.parameters)
print('900102 parameters:', record_102.parameters)
print('900101 modified unchanged:', record_101.modified == modified_before['900101'])
print('900102 modified unchanged:', record_102.modified == modified_before['900102'])

keys_intact = all(
    record.parameters.get(key) == TAGGED[record.observation_id][key]
    for record in (record_101, record_102)
    for key in OBSERVED_SITE_PARAMETER_KEYS
)
if (
    'would update: 0' in keep_dry_stdout.getvalue()
    and 'updated: 0, unchanged: 2' in keep_real_stdout.getvalue()
    and keys_intact
):
    print('PASS: unchanged portal data leaves both records unchanged and every observed-site key in place')

dry-run stdout: Would reuse target 'Backfill Demo Object'; would leave unchanged ObservationRecord observation_id='900101' status='COMPLETED'.
Would reuse target 'Backfill Demo Object'; would leave unchanged ObservationRecord observation_id='900102' status='COMPLETED'.
Would reuse ObservationGroup 'Backfill Demo Group (900100)'.
requestgroups seen: 1, would create: 0, would update: 0, unchanged: 2, skipped: 0, targets would create: 0, groups would create: 0, groups would reuse: 1, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 2, block lookups failed: n/a (dry-run), target list: would reuse 'BACKFILL-DEMO-2026A_targets', targets would add to list: 1, would link: 0, links skipped: 0

real-run stdout: requestgroups seen: 1, created: 0, updated: 0, unchanged: 2, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 2, block lookups failed: 0, target list: reused 'BACKFILL-DE

In [9]:
moved_request = dict(_request(900101, 'COMPLETED'))
moved_request['windows'] = [{'start': '2026-07-02T00:00:00', 'end': '2026-07-03T00:00:00'}]
moved_request_group = _request_group([moved_request, _request(900102, 'COMPLETED')])

moved_stdout = io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([moved_request_group]),
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(SECOND_PASS_SCHEDULE),
    ),
):
    call_command('backfill_lco_observations', '--proposal', DEMO_PROPOSAL, stdout=moved_stdout, stderr=io.StringIO())
print('stdout:', moved_stdout.getvalue())

record_101.refresh_from_db()
print('900101 parameters:', record_101.parameters)

if (
    record_101.parameters['start'] == '2026-07-02T00:00:00'
    and record_101.parameters['end'] == '2026-07-03T00:00:00'
    and all(record_101.parameters.get(key) == TAGGED['900101'][key] for key in OBSERVED_SITE_PARAMETER_KEYS)
    and 'updated: 1, unchanged: 1' in moved_stdout.getvalue()
):
    print('PASS: the moved window was refreshed from the portal and the observed-site keys survived the update')

stdout: requestgroups seen: 1, created: 0, updated: 1, unchanged: 1, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 2, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-2026A_targets', targets added to list: 1, system links: 0, links skipped: 0

900101 parameters: {'proposal': 'BACKFILL-DEMO-2026A', 'instrument_type': '1M0-SCICAM-SINISTRO', 'start': '2026-07-02T00:00:00', 'end': '2026-07-03T00:00:00', 'observed_site': 'elp', 'observed_telescope': '1m0a', 'observed_enclosure': 'doma'}
PASS: the moved window was refreshed from the portal and the observed-site keys survived the update


## Finished records are not looked up again

The `/api/requestgroups/` listing carries no observed blocks, so every request would
otherwise cost one live `get_observation_status()` lookup (two portal requests) on every
tick, and a tick would grow longer as a proposal ages (F2).

A record whose stored state is one of the facility's terminal states, and which the portal
still reports in that same state, is therefore compared on status and parameters only, with
no lookup, and its stored `scheduled_start`/`scheduled_end` are left alone. The summary
counts it under `fallback lookups skipped`. These are still looked up: a brand-new request, a
record still pending, a record whose state changed, and a completed record that is still
missing its scheduled times. An operator run with `--recheck-unscheduled` looks such records up once
anyway (see the aborted-block section below).

The cell below re-runs the sweep over the two finished records from the cells above. It
makes no lookup at all (`live lookups made: 0`). It then dry-runs the same payload with one
extra pending request: the new request is counted under `fallback lookups needed`, and the
two finished records under `fallback lookups skipped`. The dry run writes nothing, so the
extra request never exists.


In [10]:
from tom_observations.facilities.lco import LCOFacility

print('facility terminal states:', LCOFacility().get_terminal_observing_states())

# Real run over the payload the stored records already match: both are finished and the portal
# still reports them in the same state, so no live lookup is made.
skip_stdout = io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([moved_request_group]),
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(SECOND_PASS_SCHEDULE),
    ) as skip_status,
):
    call_command('backfill_lco_observations', '--proposal', DEMO_PROPOSAL, stdout=skip_stdout, stderr=io.StringIO())
print('stdout:', skip_stdout.getvalue())
print('live lookups made:', skip_status.call_count)

# Dry run over the same payload plus one brand-new pending request: it is still counted as needing a lookup.
with_new_request_group = _request_group(moved_request_group['requests'] + [_request(900103, 'PENDING')])
new_dry_stdout = io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        return_value=_page_response([with_new_request_group]),
    ),
    patch('solsys_code.observation_blocks.FomoLCOFacility.get_observation_status') as _new_dry_status,
):
    call_command(
        'backfill_lco_observations',
        '--proposal',
        DEMO_PROPOSAL,
        '--dry-run',
        stdout=new_dry_stdout,
        stderr=io.StringIO(),
    )
print('dry-run stdout:', new_dry_stdout.getvalue())

if (
    'updated: 0, unchanged: 2' in skip_stdout.getvalue()
    and 'fallback lookups needed: 0, fallback lookups skipped: 2' in skip_stdout.getvalue()
    and skip_status.call_count == 0
    and 'would create: 1' in new_dry_stdout.getvalue()
    and 'fallback lookups needed: 1, fallback lookups skipped: 2' in new_dry_stdout.getvalue()
):
    print(
        'PASS: finished records are skipped with zero lookups, and a brand-new request is still counted as needing one'
    )

facility terminal states: ['COMPLETED', 'WINDOW_EXPIRED', 'CANCELED', 'FAILURE_LIMIT_REACHED', 'NOT_ATTEMPTED']
stdout: requestgroups seen: 1, created: 0, updated: 0, unchanged: 2, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 2, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-2026A_targets', targets added to list: 1, system links: 0, links skipped: 0

live lookups made: 0
dry-run stdout: Would reuse target 'Backfill Demo Object'; would leave unchanged ObservationRecord observation_id='900101' status='COMPLETED'.
Would reuse target 'Backfill Demo Object'; would leave unchanged ObservationRecord observation_id='900102' status='COMPLETED'.
Would reuse target 'Backfill Demo Object'; would create ObservationRecord observation_id='900103' status='PENDING'.
Would reuse ObservationGroup 'Backfill Demo Group (900100)'.
requestgroups seen: 1, would create: 1, would update: 0, unchanged: 

## Seeding the watched list, and running with no arguments at all

The whole of what an operator does to widen discovery is add a row here -- no
redeploy, no command-line argument at all (SC 2, D-06, D-07). Two `WatchedProposal`
rows are created below with placeholder codes derived from `DEMO_PROPOSAL` (a
`-B`-suffixed sibling), one of them with a `target_list_name` override, then
`call_command('backfill_lco_observations')` is invoked with **no** `--proposal` --
the exact bare invocation the unattended runner's discovery step uses every tick.
Both watched codes are swept in the same run, each through its own
`RequestGroup` payload (`make_request` is patched with a proposal-aware
`side_effect` below, since a bare sweep queries the portal once per watched row).


**Note (CR-02, 36-REVIEW.md):** this bare invocation must never be combined with `--created-after`/`--created-before`/`--username`/`--target-list` -- the watched-list sweep has no window argument at all and takes its overrides from each row above instead, so the command now raises `CommandError` rather than silently discarding a flag that looked like it applied.

In [11]:
from urllib.parse import parse_qs, urlparse

from solsys_code.models import WatchedProposal

DEMO_PROPOSAL_B = f'{DEMO_PROPOSAL}-B'
DEMO_TARGET_NAME_B = 'Backfill Demo Object B'
DEMO_GROUP_NAME_FRAGMENT_B = 'Backfill Demo Group B'


def _request_for(request_id, state, target_name):
    return {
        'id': request_id,
        'state': state,
        'windows': [{'start': '2026-07-01T00:00:00', 'end': '2026-07-02T00:00:00'}],
        'configurations': [_configuration(target_name)],
    }


watched_request_group_a = _request_group([_request_for(900301, 'PENDING', DEMO_TARGET_NAME)])
watched_request_group_b = {
    'id': 900400,
    'name': DEMO_GROUP_NAME_FRAGMENT_B,
    'proposal': DEMO_PROPOSAL_B,
    'state': 'PENDING',
    'created': '2026-07-01T00:00:00Z',
    'requests': [_request_for(900401, 'PENDING', DEMO_TARGET_NAME_B)],
}
WATCHED_PAYLOADS = {DEMO_PROPOSAL: watched_request_group_a, DEMO_PROPOSAL_B: watched_request_group_b}

WATCHED_SCHEDULE = {
    '900301': {'scheduled_start': '2026-07-01T00:10:00+00:00', 'scheduled_end': '2026-07-01T00:20:00+00:00'},
    '900401': {'scheduled_start': '2026-07-03T00:10:00+00:00', 'scheduled_end': '2026-07-03T00:20:00+00:00'},
}


def _watched_list_make_request(method, url, **kwargs):
    proposal_code = parse_qs(urlparse(url).query)['proposal'][0]
    return _page_response([WATCHED_PAYLOADS[proposal_code]])


WatchedProposal.objects.create(proposal_code=DEMO_PROPOSAL, is_active=True)
WatchedProposal.objects.create(
    proposal_code=DEMO_PROPOSAL_B, is_active=True, target_list_name='backfill-demo-watchlist-B'
)

watched_stdout, watched_stderr = io.StringIO(), io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        side_effect=_watched_list_make_request,
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup(WATCHED_SCHEDULE),
    ),
):
    call_command('backfill_lco_observations', stdout=watched_stdout, stderr=watched_stderr)

print('stdout:', watched_stdout.getvalue())
if watched_stderr.getvalue():
    print('stderr:', watched_stderr.getvalue())

print(
    '900301 (proposal A) created:', ObservationRecord.objects.filter(facility='LCO', observation_id='900301').exists()
)
print(
    '900401 (proposal B) created:', ObservationRecord.objects.filter(facility='LCO', observation_id='900401').exists()
)

Observation change state hook: Backfill Demo Object @ LCO from None to PENDING


Target post save hook: Backfill Demo Object B created: True


Observation change state hook: Backfill Demo Object B @ LCO from None to PENDING


stdout: Swept 2 watched proposal(s), failed: 0

900301 (proposal A) created: True
900401 (proposal B) created: True


## CR-02: the bare-invocation flags actually raise `CommandError`

The markdown note above states the contract; this cell exercises it. Combining the
bare (no `--proposal`) invocation with any of `--created-after`, `--created-before`,
`--username`, or `--target-list` now raises `CommandError` instead of silently
discarding the flag -- the watched-list sweep takes its overrides from each
`WatchedProposal` row above, so a window flag on the bare invocation could never have
done anything even before this guard existed.

In [12]:
from django.core.management.base import CommandError

try:
    call_command('backfill_lco_observations', created_after='2026-01-01')
except CommandError as exc:
    print('CommandError (expected):', exc)

CommandError (expected): --created-after requires --proposal; the watched-list sweep takes its overrides from each WatchedProposal row.


## The bookkeeping the sweep writes back

This is exactly what an operator reads in the admin's `Watched proposals`
changelist when nothing has appeared on the calendar: `last_run_at` and
`last_run_summary` on each row, written after every sweep of that row --
success or failure -- never hand-typed.


In [13]:
watched_a = WatchedProposal.objects.get(proposal_code=DEMO_PROPOSAL)
watched_b = WatchedProposal.objects.get(proposal_code=DEMO_PROPOSAL_B)

print('A last_run_at     :', watched_a.last_run_at)
print('A last_run_summary:', watched_a.last_run_summary)
print('B last_run_at     :', watched_b.last_run_at)
print('B last_run_summary:', watched_b.last_run_summary)

if watched_a.last_run_at is not None and watched_a.last_run_summary.startswith('requestgroups seen:'):
    print('PASS: watched proposal A recorded a real sweep summary')
if watched_b.last_run_at is not None and watched_b.last_run_summary.startswith('requestgroups seen:'):
    print('PASS: watched proposal B recorded a real sweep summary')

A last_run_at     : 2026-10-04 20:48:27.015021+00:00
A last_run_summary: requestgroups seen: 1, created: 1, updated: 0, unchanged: 0, skipped: 0, targets created: 0, groups created: 0, groups reused: 0, embedded blocks: 0, fallback lookups needed: 1, fallback lookups skipped: 0, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-2026A_targets', targets added to list: 1, system links: 0, links skipped: 0
B last_run_at     : 2026-10-04 20:48:27.054644+00:00
B last_run_summary: requestgroups seen: 1, created: 1, updated: 0, unchanged: 0, skipped: 0, targets created: 1, groups created: 0, groups reused: 0, embedded blocks: 0, fallback lookups needed: 1, fallback lookups skipped: 0, block lookups failed: 0, target list: created 'backfill-demo-watchlist-B', targets added to list: 1, system links: 0, links skipped: 0
PASS: watched proposal A recorded a real sweep summary
PASS: watched proposal B recorded a real sweep summary


## Per-proposal failure isolation

One bad proposal never blocks the rest (D-09). Below, `make_request` is patched to
raise for proposal A's request and return a normal page for proposal B's; running
the watched-list sweep again shows proposal A's row recording
`failed: <ExceptionClassName>` -- the exception's class name only, **never** its
message, which could otherwise embed portal request or response content -- while
proposal B's row still records a real counter summary line and its new record
(a fresh request, `900402`, proving B's own sweep still ran to completion) is
still created.


In [14]:
from django.core.management.base import CommandError

watched_request_group_b_second = {
    'id': 900410,
    'name': f'{DEMO_GROUP_NAME_FRAGMENT_B} 2',
    'proposal': DEMO_PROPOSAL_B,
    'state': 'PENDING',
    'created': '2026-07-01T00:00:00Z',
    'requests': [_request_for(900402, 'PENDING', DEMO_TARGET_NAME_B)],
}


def _failing_make_request(method, url, **kwargs):
    proposal_code = parse_qs(urlparse(url).query)['proposal'][0]
    if proposal_code == DEMO_PROPOSAL:
        raise ConnectionError('simulated portal outage for proposal A')
    return _page_response([watched_request_group_b_second])


second_watched_stdout, second_watched_stderr = io.StringIO(), io.StringIO()
with (
    patch(
        'solsys_code.management.commands.backfill_lco_observations.make_request',
        side_effect=_failing_make_request,
    ),
    patch(
        'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
        side_effect=_status_lookup({**WATCHED_SCHEDULE, '900402': WATCHED_SCHEDULE['900401']}),
    ),
):
    try:
        call_command('backfill_lco_observations', stdout=second_watched_stdout, stderr=second_watched_stderr)
    except CommandError as exc:
        print('CommandError (expected -- one watched proposal failed):', exc)

print('stdout:', second_watched_stdout.getvalue())
if second_watched_stderr.getvalue():
    print('stderr:', second_watched_stderr.getvalue())

watched_a.refresh_from_db()
watched_b.refresh_from_db()
print('A last_run_summary:', watched_a.last_run_summary)
print('B last_run_summary:', watched_b.last_run_summary)
print(
    '900402 (proposal B, second sweep) created:',
    ObservationRecord.objects.filter(facility='LCO', observation_id='900402').exists(),
)

if watched_a.last_run_summary.startswith('failed:'):
    print("PASS: proposal A's failure is recorded, class name only, never its message")
if watched_b.last_run_summary.startswith('requestgroups seen:'):
    print("PASS: proposal B's sweep still ran to completion despite A's failure")

Observation change state hook: Backfill Demo Object B @ LCO from None to PENDING


CommandError (expected -- one watched proposal failed): 1 watched proposal(s) failed: BACKFILL-DEMO-2026A
stdout: Swept 2 watched proposal(s), failed: 1

stderr: Proposal 'BACKFILL-DEMO-2026A': failed: ConnectionError

A last_run_summary: failed: ConnectionError
B last_run_summary: requestgroups seen: 1, created: 1, updated: 0, unchanged: 0, skipped: 0, targets created: 0, groups created: 0, groups reused: 0, embedded blocks: 0, fallback lookups needed: 1, fallback lookups skipped: 0, block lookups failed: 0, target list: reused 'backfill-demo-watchlist-B', targets added to list: 1, system links: 0, links skipped: 0
900402 (proposal B, second sweep) created: True
PASS: proposal A's failure is recorded, class name only, never its message
PASS: proposal B's sweep still ran to completion despite A's failure


## Exact matches link themselves (system links)

A record the sweep touches is linked to a run automatically when it matches **exactly one**
`APPROVED` run, with no person involved:

- the run has the same proposal code as the record, carries the record's target, and its window
  contains the record's window (UTC dates, inclusive); or
- when no run with that proposal carries the record's target, the record's campaign holds exactly
  one `APPROVED`, dated run with that proposal, and that run's window contains the record's.

The link is a *system link*: `confirmed_by` is empty and the Confirmed table and the admin show
it as **System (exact match)**. Anything else -- two matching runs, a campaign with two runs on
the same proposal, a target the campaign does not hold -- stays in the attribution queue for a
person. The summary line gains `system links: N, links skipped: M` (`would link: N` under
`--dry-run`), each link prints one line naming the run and the basis, and a second pass links
nothing new and leaves `confirmed_at` alone.

This section uses its own proposal code, targets and campaigns, so the earlier cells' output is
unaffected. Three records are swept:

- `900501` targets `Link Demo Comet Alpha`, which `run_alpha` carries -- linked by target;
- `900502` targets `Link Demo Field Beta`, which no run carries but whose campaign holds only
  `run_alpha` -- linked by the campaign fallback;
- `900503` targets `Link Demo Comet Delta`, whose campaign holds two runs on the proposal -- ambiguous,
  so it stays in the queue.

In [15]:
import datetime

from tom_targets.tests.factories import NonSiderealTargetFactory

from solsys_code import campaign_attribution
from solsys_code.models import CampaignRun, CampaignRunObservation

DEMO_LINK_PROPOSAL = 'BACKFILL-DEMO-LINK-2026B'
DEMO_LINK_GROUP_NAME = 'Backfill Link Demo Group'

link_alpha = NonSiderealTargetFactory.create(name='Link Demo Comet Alpha')
link_beta = NonSiderealTargetFactory.create(name='Link Demo Field Beta')
link_delta = NonSiderealTargetFactory.create(name='Link Demo Comet Delta')
link_x = NonSiderealTargetFactory.create(name='Link Demo Comet X')
link_y = NonSiderealTargetFactory.create(name='Link Demo Comet Y')

link_campaign = TargetList.objects.create(name='Link Demo Campaign')
link_campaign.targets.add(link_alpha, link_beta)
shared_campaign = TargetList.objects.create(name='Link Demo Shared Campaign')
shared_campaign.targets.add(link_delta, link_x, link_y)


def _approved_run(campaign, target, window_end=datetime.date(2026, 7, 5)):
    return CampaignRun.objects.create(
        campaign=campaign,
        target=target,
        proposal_code=DEMO_LINK_PROPOSAL,
        telescope_class='1m0',
        source=CampaignRun.Source.LCO_QUEUE,
        approval_status=CampaignRun.ApprovalStatus.APPROVED,
        telescope_instrument='1m0/Sinistro',
        window_start=datetime.date(2026, 6, 28),
        window_end=window_end,
    )


run_alpha = _approved_run(link_campaign, link_alpha)
run_x = _approved_run(shared_campaign, link_x)
run_y = _approved_run(shared_campaign, link_y, window_end=datetime.date(2026, 7, 6))
print('run_alpha pk:', run_alpha.pk, '| run_x pk:', run_x.pk, '| run_y pk:', run_y.pk)

link_request_group = {
    'id': 900500,
    'name': DEMO_LINK_GROUP_NAME,
    'proposal': DEMO_LINK_PROPOSAL,
    'state': 'COMPLETED',
    'created': '2026-07-01T00:00:00Z',
    'requests': [
        _request_for(900501, 'COMPLETED', 'Link Demo Comet Alpha'),
        _request_for(900502, 'COMPLETED', 'Link Demo Field Beta'),
        _request_for(900503, 'COMPLETED', 'Link Demo Comet Delta'),
    ],
}
LINK_SCHEDULE = {
    '900501': {'scheduled_start': '2026-07-01T00:10:00+00:00', 'scheduled_end': '2026-07-01T00:20:00+00:00'},
    '900502': {'scheduled_start': '2026-07-02T00:10:00+00:00', 'scheduled_end': '2026-07-02T00:20:00+00:00'},
    '900503': {'scheduled_start': '2026-07-03T00:10:00+00:00', 'scheduled_end': '2026-07-03T00:20:00+00:00'},
}


def _sweep_link_proposal(*extra_args):
    out, err = io.StringIO(), io.StringIO()
    with (
        patch(
            'solsys_code.management.commands.backfill_lco_observations.make_request',
            return_value=_page_response([link_request_group]),
        ),
        patch(
            'solsys_code.observation_blocks.FomoLCOFacility.get_observation_status',
            side_effect=_status_lookup(LINK_SCHEDULE),
        ),
    ):
        call_command('backfill_lco_observations', '--proposal', DEMO_LINK_PROPOSAL, *extra_args, stdout=out, stderr=err)
    return out.getvalue(), err.getvalue()


dry_stdout, dry_stderr = _sweep_link_proposal('--dry-run')
print('stdout:', dry_stdout)
if dry_stderr:
    print('stderr:', dry_stderr)
print(
    'system-link rows written by the dry run:',
    CampaignRunObservation.objects.filter(run__proposal_code=DEMO_LINK_PROPOSAL).count(),
)

Target post save hook: Link Demo Comet Alpha created: True


Target post save hook: Link Demo Comet Alpha created: False


Target post save hook: Link Demo Field Beta created: True


Target post save hook: Link Demo Field Beta created: False


Target post save hook: Link Demo Comet Delta created: True


Target post save hook: Link Demo Comet Delta created: False


Target post save hook: Link Demo Comet X created: True


Target post save hook: Link Demo Comet X created: False


Target post save hook: Link Demo Comet Y created: True


Target post save hook: Link Demo Comet Y created: False


run_alpha pk: 1 | run_x pk: 2 | run_y pk: 3
stdout: Would reuse target 'Link Demo Comet Alpha'; would create ObservationRecord observation_id='900501' status='COMPLETED'.
Would system-link ObservationRecord observation_id='900501' to CampaignRun #1 (proposal + target + window).
Would reuse target 'Link Demo Field Beta'; would create ObservationRecord observation_id='900502' status='COMPLETED'.
Would system-link ObservationRecord observation_id='900502' to CampaignRun #1 (proposal unique within campaign + window).
Would reuse target 'Link Demo Comet Delta'; would create ObservationRecord observation_id='900503' status='COMPLETED'.
Would create ObservationGroup 'Backfill Link Demo Group (900500)'.
requestgroups seen: 1, would create: 3, would update: 0, unchanged: 0, skipped: 0, targets would create: 0, groups would create: 1, groups would reuse: 0, embedded blocks: 0, fallback lookups needed: 3, fallback lookups skipped: 0, block lookups failed: n/a (dry-run), target list: would create 

In [16]:
real_link_stdout, real_link_stderr = _sweep_link_proposal()
print('stdout:', real_link_stdout)
if real_link_stderr:
    print('stderr:', real_link_stderr)

links = {}
for observation_id in ('900501', '900502', '900503'):
    record = ObservationRecord.objects.get(facility='LCO', observation_id=observation_id)
    link = CampaignRunObservation.objects.filter(observation_record=record).first()
    links[observation_id] = link
    print(
        observation_id,
        '| target:',
        record.target.name,
        '| linked run pk:',
        link.run_id if link else 'no link',
        '| confirmed by:',
        link.confirmed_by_label() if link else '-',
    )

delta_record = ObservationRecord.objects.get(facility='LCO', observation_id='900503')
backlog = {g.orphan.pk: g for g in campaign_attribution.record_attribution_backlog()}
in_backlog = delta_record.pk in backlog
print('900503 is in the attribution queue:', in_backlog)
if in_backlog:
    print('900503 candidate run pks:', [c.run.pk for c in backlog[delta_record.pk].candidates])

if (
    'system links: 2, links skipped: 0' in real_link_stdout
    and 'proposal + target + window' in real_link_stdout
    and 'proposal unique within campaign + window' in real_link_stdout
    and links['900501'] is not None
    and links['900501'].run_id == run_alpha.pk
    and links['900502'] is not None
    and links['900502'].run_id == run_alpha.pk
    and links['900503'] is None
    and in_backlog
    and links['900501'].confirmed_by_label() == 'System (exact match)'
    and links['900502'].confirmed_by_label() == 'System (exact match)'
):
    print('PASS: one record linked by target, one by campaign fallback, the ambiguous one left in the queue')

Observation change state hook: Link Demo Comet Alpha @ LCO from None to COMPLETED


Observation change state hook: Link Demo Field Beta @ LCO from None to COMPLETED


Observation change state hook: Link Demo Comet Delta @ LCO from None to COMPLETED


stdout: System-linked ObservationRecord observation_id='900501' to CampaignRun #1 (proposal + target + window).
System-linked ObservationRecord observation_id='900502' to CampaignRun #1 (proposal unique within campaign + window).
requestgroups seen: 1, created: 3, updated: 0, unchanged: 0, skipped: 0, targets created: 0, groups created: 1, groups reused: 0, embedded blocks: 0, fallback lookups needed: 3, fallback lookups skipped: 0, block lookups failed: 0, target list: created 'BACKFILL-DEMO-LINK-2026B_targets', targets added to list: 3, system links: 2, links skipped: 0

900501 | target: Link Demo Comet Alpha | linked run pk: 1 | confirmed by: System (exact match)
900502 | target: Link Demo Field Beta | linked run pk: 1 | confirmed by: System (exact match)
900503 | target: Link Demo Comet Delta | linked run pk: no link | confirmed by: -
900503 is in the attribution queue: True
900503 candidate run pks: [2, 3]
PASS: one record linked by target, one by campaign fallback, the ambiguous 

In [17]:
confirmed_before = {oid: link.confirmed_at for oid, link in links.items() if link is not None}
second_stdout, second_stderr = _sweep_link_proposal()
print('stdout:', second_stdout)
if second_stderr:
    print('stderr:', second_stderr)

confirmed_after = {
    oid: CampaignRunObservation.objects.get(pk=link.pk).confirmed_at for oid, link in links.items() if link is not None
}
print('confirmed_at unchanged:', confirmed_before == confirmed_after)
print(
    'link rows for this proposal:', CampaignRunObservation.objects.filter(run__proposal_code=DEMO_LINK_PROPOSAL).count()
)

if 'system links: 0' in second_stdout and confirmed_before == confirmed_after:
    print('PASS: the second pass wrote no new link and left confirmed_at unchanged')

stdout: requestgroups seen: 1, created: 0, updated: 0, unchanged: 3, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 3, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-LINK-2026B_targets', targets added to list: 3, system links: 0, links skipped: 0

confirmed_at unchanged: True
link rows for this proposal: 2
PASS: the second pass wrote no new link and left confirmed_at unchanged


## A block that started and was aborted retires its allocation night

A request can expire or be cancelled after one of its observing blocks started and took data and
was then aborted. FOMO counts such a block: the sweep takes a request's scheduled times from the
**first completed block, else the last aborted or in-progress block, else the last pending block**
(TOM Toolkit's own status call ignores an aborted block). A request that never got a block at all
has no times and keeps every allocation night of its run.

Records stored before this rule have no times. Because they are finished and the portal still
reports the same state, the per-tick skip above leaves them alone on every sweep.
`--recheck-unscheduled` (with `--proposal`, or bare for every watched proposal) looks up every
record that is missing a scheduled time once, so those records pick up an aborted block's times;
the unattended runner never passes it, so its lookups per tick stay bounded.

The next three cells build a per-night classical run at La Silla and two records stored the old
way -- request `900601` (expired, its only block was aborted) and `900602` (cancelled, never
scheduled) -- each linked to the run. An ordinary sweep then changes nothing and makes no portal
lookup, and a `--recheck-unscheduled` sweep gives `900601` its block's times, removes exactly that
night's allocation entry, and leaves `900602` without times and with its night.

In [18]:
from zoneinfo import ZoneInfo

from tom_calendar.models import CalendarEvent

from solsys_code import campaign_utils
from solsys_code.allocation_projector import allocation_events
from solsys_code.campaign_reconciler import reconcile_run
from solsys_code.management.commands.backfill_lco_observations import _build_parameters
from solsys_code.observation_blocks import select_schedule_block
from solsys_code.solsys_code_observatory.models import Observatory
from solsys_code.telescope_runs import observing_night

DEMO_ABORT_PROPOSAL = 'BACKFILL-DEMO-ABORT-2026B'
DEMO_ABORT_TARGET_NAME = 'Abort Demo Comet'
DEMO_ABORT_GROUP_NAME = 'Backfill Abort Demo Group'

# FOMO's block rule on four sample lists.
aborted = {'state': 'ABORTED', 'start': '2026-07-01T01:00:00Z', 'end': '2026-07-01T01:40:00Z'}
pending = {'state': 'PENDING', 'start': '2026-07-02T01:00:00Z', 'end': '2026-07-02T01:40:00Z'}
completed = {'state': 'COMPLETED', 'start': '2026-07-03T01:00:00Z', 'end': '2026-07-03T01:40:00Z'}
cancelled = {'state': 'CANCELED', 'start': '2026-07-01T01:00:00Z', 'end': None}
for label, sample in (
    ('aborted only', [aborted]),
    ('pending then aborted', [pending, aborted]),
    ('aborted then completed', [aborted, completed]),
    ('cancelled only', [cancelled]),
):
    chosen = select_schedule_block(sample)
    print(f'{label:24s} -> {chosen["state"] if chosen else None}')

abort_site = Observatory.objects.create(
    obscode='809',
    name='ESO, La Silla',
    short_name='NTT',
    lat=-29.2567,
    lon=-70.7300,
    altitude=2347,
    timezone='America/Santiago',
    observations_type=Observatory.OPTICAL_OBSTYPE,
)
abort_target = NonSiderealTargetFactory.create(name=DEMO_ABORT_TARGET_NAME)
abort_run = CampaignRun.objects.create(
    campaign=None,
    target=abort_target,
    proposal_code=DEMO_ABORT_PROPOSAL,
    source=CampaignRun.Source.CLASSICAL_FILE,
    approval_status=CampaignRun.ApprovalStatus.APPROVED,
    telescope_instrument='NTT/EFOSC2',
    site=abort_site,
    site_raw='809',
    window_start=datetime.date(2026, 6, 29),
    window_end=datetime.date(2026, 7, 2),
)
reconcile_run(abort_run)

abort_request_group = {
    'id': 900600,
    'name': DEMO_ABORT_GROUP_NAME,
    'proposal': DEMO_ABORT_PROPOSAL,
    'state': 'WINDOW_EXPIRED',
    'created': '2026-07-01T00:00:00Z',
    'requests': [
        _request_for(900601, 'WINDOW_EXPIRED', DEMO_ABORT_TARGET_NAME),
        _request_for(900602, 'CANCELED', DEMO_ABORT_TARGET_NAME),
    ],
}

# Records as they were stored under TOM's old rule: finished, no scheduled times, system-linked.
for request in abort_request_group['requests']:
    legacy_record = ObservationRecord.objects.create(
        target=abort_target,
        facility='LCO',
        observation_id=str(request['id']),
        status=request['state'],
        parameters=_build_parameters(abort_request_group, request),
    )
    campaign_utils.create_system_link(legacy_record, abort_run)


def _allocation_urls():
    return sorted(allocation_events(abort_run).values_list('url', flat=True))


nights_before = _allocation_urls()
print('allocation nights before:', nights_before)

Target post save hook: Abort Demo Comet created: True


aborted only             -> ABORTED
pending then aborted     -> ABORTED
aborted then completed   -> COMPLETED
cancelled only           -> None


Target post save hook: Abort Demo Comet created: False


Observation change state hook: Abort Demo Comet @ LCO from None to WINDOW_EXPIRED


Observation change state hook: Abort Demo Comet @ LCO from None to CANCELED


allocation nights before: ['ALLOC:4:2026-06-29', 'ALLOC:4:2026-06-30', 'ALLOC:4:2026-07-01', 'ALLOC:4:2026-07-02']


In [19]:
def _abort_portal_lookup(method, url, **kwargs):
    # The two portal GETs FOMO's facility makes: the request, then its observation blocks.
    response = MagicMock()
    if url.endswith('/observations/'):
        request_id = url.rsplit('/', 3)[-3]
        response.json.return_value = [aborted] if request_id == '900601' else []
    else:
        request_id = url.rsplit('/', 1)[-1]
        response.json.return_value = {'state': 'WINDOW_EXPIRED' if request_id == '900601' else 'CANCELED'}
    return response


def _abort_sweep(*extra_args):
    out, err = io.StringIO(), io.StringIO()
    with (
        patch(
            'solsys_code.management.commands.backfill_lco_observations.make_request',
            return_value=_page_response([abort_request_group]),
        ),
        patch('solsys_code.observation_blocks.make_request', side_effect=_abort_portal_lookup) as portal,
    ):
        call_command(
            'backfill_lco_observations', '--proposal', DEMO_ABORT_PROPOSAL, *extra_args, stdout=out, stderr=err
        )
    return out.getvalue(), err.getvalue(), portal.call_count


# An ordinary sweep: both records are finished and the portal still reports the same state.
plain_stdout, plain_stderr, plain_lookups = _abort_sweep()
print('stdout:', plain_stdout)
if plain_stderr:
    print('stderr:', plain_stderr)
print('portal lookups made:', plain_lookups)
nights_after_plain = _allocation_urls()
print('allocation nights:', nights_after_plain)

if 'fallback lookups skipped: 2' in plain_stdout and plain_lookups == 0 and nights_after_plain == nights_before:
    print('PASS: without --recheck-unscheduled the legacy records are left alone with zero portal lookups')

stdout: requestgroups seen: 1, created: 0, updated: 0, unchanged: 2, skipped: 0, targets created: 0, groups created: 1, groups reused: 0, embedded blocks: 0, fallback lookups needed: 0, fallback lookups skipped: 2, block lookups failed: 0, target list: created 'BACKFILL-DEMO-ABORT-2026B_targets', targets added to list: 1, system links: 0, links skipped: 0

portal lookups made: 0
allocation nights: ['ALLOC:4:2026-06-29', 'ALLOC:4:2026-06-30', 'ALLOC:4:2026-07-01', 'ALLOC:4:2026-07-02']
PASS: without --recheck-unscheduled the legacy records are left alone with zero portal lookups


In [20]:
# The one-time catch-up: every record missing a scheduled time is looked up once.
print('sweeping', DEMO_ABORT_PROPOSAL, 'with --recheck-unscheduled')
recheck_stdout, recheck_stderr, recheck_lookups = _abort_sweep('--recheck-unscheduled')
print('stdout:', recheck_stdout)
if recheck_stderr:
    print('stderr:', recheck_stderr)
print('portal lookups made:', recheck_lookups)

abort_record = ObservationRecord.objects.get(facility='LCO', observation_id='900601')
never_record = ObservationRecord.objects.get(facility='LCO', observation_id='900602')
for record in (abort_record, never_record):
    print(record.observation_id, '|', record.status, '| start:', record.scheduled_start, '| end:', record.scheduled_end)

nights_after = _allocation_urls()
print('allocation nights after:', nights_after)
retired_url = None
if abort_record.scheduled_start is not None:
    retired_night = observing_night(abort_record.scheduled_start, ZoneInfo('America/Santiago'))
    retired_url = f'ALLOC:{abort_run.pk}:{retired_night.isoformat()}'
print('night retired by the aborted block:', retired_url)

if (
    abort_record.scheduled_start is not None
    and abort_record.scheduled_start.isoformat() == '2026-07-01T01:00:00+00:00'
    and abort_record.scheduled_end.isoformat() == '2026-07-01T01:40:00+00:00'
    and retired_url in nights_before
    and retired_url not in nights_after
    and len(nights_before) - len(nights_after) == 1
    and never_record.scheduled_start is None
    and never_record.scheduled_end is None
    and 'fallback lookups needed: 2' in recheck_stdout
):
    print('PASS: the aborted block retired its night')

sweeping BACKFILL-DEMO-ABORT-2026B with --recheck-unscheduled


stdout: requestgroups seen: 1, created: 0, updated: 1, unchanged: 1, skipped: 0, targets created: 0, groups created: 0, groups reused: 1, embedded blocks: 0, fallback lookups needed: 2, fallback lookups skipped: 0, block lookups failed: 0, target list: reused 'BACKFILL-DEMO-ABORT-2026B_targets', targets added to list: 1, system links: 0, links skipped: 0

portal lookups made: 4
900601 | WINDOW_EXPIRED | start: 2026-07-01 01:00:00+00:00 | end: 2026-07-01 01:40:00+00:00
900602 | CANCELED | start: None | end: None
allocation nights after: ['ALLOC:4:2026-06-29', 'ALLOC:4:2026-07-01', 'ALLOC:4:2026-07-02']
night retired by the aborted block: ALLOC:4:2026-06-30
PASS: the aborted block retired its night


## Cleanup

This notebook is DB-dependent and creates real rows in a throwaway scratch database, never
the developer database. Clean up everything created above so the scratch database ends empty
of demo rows; the next cell block then removes the scratch database itself.


In [21]:
ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT).delete()
ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900101', '900102']).delete()
Target.objects.filter(name=DEMO_TARGET_NAME).delete()
TargetList.objects.filter(name=f'{DEMO_PROPOSAL}_targets').delete()

# Watched-list demo cells: WatchedProposal rows, their records/group/target, and B's
# overridden TargetList name (DEMO_PROPOSAL's own touched-target list is the same
# f'{DEMO_PROPOSAL}_targets' list already deleted above).
WatchedProposal.objects.filter(proposal_code__in=[DEMO_PROPOSAL, DEMO_PROPOSAL_B]).delete()
ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT_B).delete()
ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900301', '900401', '900402']).delete()
Target.objects.filter(name=DEMO_TARGET_NAME_B).delete()
TargetList.objects.filter(name='backfill-demo-watchlist-B').delete()

# System-link demo cells: runs (their links cascade), records, group, targets, campaigns, touched-target list.
CampaignRun.objects.filter(proposal_code=DEMO_LINK_PROPOSAL).delete()
ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900501', '900502', '900503']).delete()
ObservationGroup.objects.filter(name=DEMO_LINK_GROUP_NAME).delete()
LINK_TARGET_NAMES = [
    'Link Demo Comet Alpha',
    'Link Demo Field Beta',
    'Link Demo Comet Delta',
    'Link Demo Comet X',
    'Link Demo Comet Y',
]
Target.objects.filter(name__in=LINK_TARGET_NAMES).delete()
TargetList.objects.filter(
    name__in=['Link Demo Campaign', 'Link Demo Shared Campaign', f'{DEMO_LINK_PROPOSAL}_targets']
).delete()

# Aborted-block demo cells: the run's allocation events and the two records' own projected events,
# the run (its links cascade), the records, the target, the touched-target list and the observatory.
abort_run_pk = abort_run.pk
allocation_events(abort_run).delete()
CalendarEvent.objects.filter(
    telescope_label_meta__observation_record__facility='LCO',
    telescope_label_meta__observation_record__observation_id__in=['900601', '900602'],
).delete()
CampaignRun.objects.filter(proposal_code=DEMO_ABORT_PROPOSAL).delete()
ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900601', '900602']).delete()
ObservationGroup.objects.filter(name__startswith=DEMO_ABORT_GROUP_NAME).delete()
Target.objects.filter(name=DEMO_ABORT_TARGET_NAME).delete()
TargetList.objects.filter(name=f'{DEMO_ABORT_PROPOSAL}_targets').delete()
Observatory.objects.filter(obscode='809').delete()

print(
    'records remaining:',
    ObservationRecord.objects.filter(
        facility='LCO', observation_id__in=['900101', '900102', '900301', '900401', '900402']
    ).count(),
)
print(
    'groups remaining :',
    ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT).count()
    + ObservationGroup.objects.filter(name__startswith=DEMO_GROUP_NAME_FRAGMENT_B).count(),
)
print('target remaining :', Target.objects.filter(name__in=[DEMO_TARGET_NAME, DEMO_TARGET_NAME_B]).exists())
print(
    'target list remaining:',
    TargetList.objects.filter(name__in=[f'{DEMO_PROPOSAL}_targets', 'backfill-demo-watchlist-B']).exists(),
)
print(
    'watched proposals remaining:',
    WatchedProposal.objects.filter(proposal_code__in=[DEMO_PROPOSAL, DEMO_PROPOSAL_B]).exists(),
)
print('link runs remaining:', CampaignRun.objects.filter(proposal_code=DEMO_LINK_PROPOSAL).count())
print(
    'link records remaining:',
    ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900501', '900502', '900503']).count(),
)
print('link group remaining:', ObservationGroup.objects.filter(name=DEMO_LINK_GROUP_NAME).exists())
print('link targets remaining:', Target.objects.filter(name__in=LINK_TARGET_NAMES).exists())
print(
    'link campaigns remaining:',
    TargetList.objects.filter(
        name__in=['Link Demo Campaign', 'Link Demo Shared Campaign', f'{DEMO_LINK_PROPOSAL}_targets']
    ).exists(),
)
print('abort runs remaining:', CampaignRun.objects.filter(proposal_code=DEMO_ABORT_PROPOSAL).count())
print(
    'abort allocation events remaining:',
    CalendarEvent.objects.filter(url__startswith=f'ALLOC:{abort_run_pk}:').count(),
)
print(
    'abort records remaining:',
    ObservationRecord.objects.filter(facility='LCO', observation_id__in=['900601', '900602']).count(),
)
print('abort target remaining:', Target.objects.filter(name=DEMO_ABORT_TARGET_NAME).exists())
print('abort observatory remaining:', Observatory.objects.filter(obscode='809').exists())

Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


Total removed orphan object permissions instances: 0


records remaining: 0
groups remaining : 0
target remaining : False
target list remaining: False
watched proposals remaining: False
link runs remaining: 0
link records remaining: 0
link group remaining: False
link targets remaining: False
link campaigns remaining: False
abort runs remaining: 0
abort allocation events remaining: 0
abort records remaining: 0
abort target remaining: False
abort observatory remaining: False


## Scratch database teardown

Removes the scratch database directory created in the setup cell above. The developer
database was never opened for writing by this notebook run.

In [22]:
import shutil

shutil.rmtree(scratch_db_dir, ignore_errors=True)
print(f'Removed scratch database directory: {scratch_db_dir}')
print('The developer database (src/fomo_db.sqlite3) was never opened for writing.')

Removed scratch database directory: /tmp/fomo-notebook-db-56d061pr
The developer database (src/fomo_db.sqlite3) was never opened for writing.
