# Generated by Django 4.2.19 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('solsys_code_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatory',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='IANA timezone name'),
        ),
    ]
